# https://github.com/JohnnyMorganz/StyLua?tab=readme-ov-file#options

syntax = "All"
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"
space_after_function_names = "Never"
block_newline_gaps = "Never"

[sort_requires]
enabled = false
